# Understanding the `numpy.ndarray` internals

In [1]:
import numpy as np

In [10]:
x = np.array([[0, 1, 2, 3],[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int8, order="C")
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int8)

In [11]:
x.strides

(4, 1)

***
### 1. Understanding strides
<mark>Question</mark> Determine the strides for the following arrays. Check your answer with `x.strides`.

In [3]:
# 1.1
y = x.reshape((2, 8))
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]], dtype=int8)

In [16]:
y.strides

(8, 1)

In [14]:
# 1.2
z = x.reshape((1, 16))
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]],
      dtype=int8)

In [15]:
z.strides

(16, 1)

In [17]:
# 1.3
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int16)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int16)

In [18]:
a.strides

(8, 2)

***
### 2. Metadata modification vs copying the data buffer

<mark>Question</mark> How do you explain the next result? Is it the same for `x.flatten()`?

In [25]:
#x = np.random.rand(3, 3)
#y = x.ravel()  #  flatten the array
#y[0] = 100.
y = x.flatten()
y[0] = 100.
x.strides
y.strides

(8,)

<mark>Question</mark> The next three cells do the same two operations: transposing a matrix and flattening it. How do you explain the difference in execution time?

In [26]:
x = np.random.rand(5000, 5000)

In [27]:
%%timeit
# 2.1
x.T
x.ravel()

386 ns ± 1.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [30]:
%%timeit
# 2.2
x.T.ravel()   #### ADD A FIGURE

404 ms ± 1.64 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
%%timeit
# 2.3
x.T
x.flatten()

15.9 ms ± 46 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
