# Basics of broadcasting
The concept [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) has to do with the way NumPy treats the arrays during operations involving different shapes. For instance, an array of shape `(5,)` added to an escalar, gives an array of shape `(5, )` where to all the elements was added the escaler:

In [2]:
import numpy as np

In [3]:
x = np.arange(5)   # of shape (5,)
x + 1.

array([1., 2., 3., 4., 5.])

An important operation in broadcasting is to create new dimensions of an array using `np.newaxis` .

In [4]:
x = np.arange(5)
x.shape

(5,)

In [20]:
%timeit x[:, np.newaxis].shape

306 ns ± 1.12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [21]:
%timeit x[np.newaxis, :].shape

307 ns ± 0.34 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


<mark>Question</mark> From what you have already learned about the `numpy.ndarray`s, the operation `x[:, np.newaxis]` allocates new memory or can it be described with only a change on the metadata?

***

Broadcasting is often usefull to perform operations that are not vectorial in the mathematical sense, in a vectorial fashion. For instance, the next cell produces the array `y` with the different of all the possible combinations of the elements of `x`.

In [8]:
x[:, np.newaxis], x[np.newaxis,:]

(array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]]))

In [12]:
y = x[:, np.newaxis] + x[np.newaxis, :]
print(y,"\n\n",y.shape)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]] 

 (5, 5)


Here what happens is that each element of the `(5, 1)` array is added the `(5,)` element of the `(1, 5)` array. This will already know that produces an array of shape `(5,)`. Repeated for the five elements, this gives a `(5, 5)` array. 

***

Let's see know how to get again the difference of all combinations of the `(3,)` elements of a `(10, 3)` array:

In [19]:
x = np.random.rand(10, 3)
x.shape, x.strides

((10, 3), (24, 8))

In [14]:
x[:, np.newaxis, :].shape

(10, 1, 3)

In [15]:
x[np.newaxis, :, :].shape

(1, 10, 3)

In [16]:
y = x[np.newaxis, :, :] - x[:, np.newaxis, :]

In [17]:
y

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.37787374, -0.25127257, -0.23446511],
        [ 0.21071955, -0.48951952, -0.81449504],
        [-0.09078163, -0.04050461, -0.0508845 ],
        [ 0.25893037, -0.66840897, -0.61543305],
        [ 0.16243632,  0.0438838 , -0.92023276],
        [ 0.29716301, -0.41989016, -0.10249453],
        [ 0.42755087, -0.27865016, -0.04598045],
        [ 0.23308922, -0.66500671, -0.48355998],
        [ 0.08134059, -0.32254185, -0.84768468]],

       [[-0.37787374,  0.25127257,  0.23446511],
        [ 0.        ,  0.        ,  0.        ],
        [-0.16715419, -0.23824695, -0.58002993],
        [-0.46865537,  0.21076796,  0.18358062],
        [-0.11894337, -0.41713639, -0.38096794],
        [-0.21543742,  0.29515638, -0.68576765],
        [-0.08071073, -0.16861758,  0.13197059],
        [ 0.04967713, -0.02737759,  0.18848466],
        [-0.14478452, -0.41373413, -0.24909487],
        [-0.29653315, -0.07126928, -0.61321957]],

       [[-0.2107

In [18]:
y.shape

(10, 10, 3)